services:
  app:
    build: .
    container_name: antriin_id
    ports:
      - 8089:8089
    volumes:
      - .:/app
  postgres_db:
    image: postgres
    ports:
      - 8088:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=super_admin
      - POSTGRES_DB=antriin-db
