services:
  app:
    build: .
    container_name: antriin_id
    ports:
      - 8089:8089
    volumes:
      - .:/app
  postgres_db:
    image: firdausraginda/antriin-db-postgres:latest
    ports:
      - 8088:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=super_admin
      - POSTGRES_DB=antriin-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
